auth_enabled: false

ingester:
  max_chunk_age: 2160h

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 12582912

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  reject_old_samples: false
  unordered_writes: true
  retention_period: 90d
  max_query_length: 0h # Default: 721h
  max_query_parallelism: 32 # Old Default: 14
  max_streams_per_user: 0
  per_stream_rate_limit: 1000MB
  ingestion_rate_mb: 1000

  

table_manager:
  retention_deletes_enabled: true
  retention_period: 90d

ruler:
  alertmanager_url: http://localhost:9093

