version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/crunchy-dashboards.yaml:/etc/grafana/provisioning/dashboards/crunchy-dashboards.yaml
    environment:
      - LOKI_URL=loki
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - DASHBOARDS_PATH=/etc/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - loki
