{
 "title": "pgBouncer Stats",
 "time": { "from": "2022-02-18T04:04:54.901Z", "to": "2022-02-25T19:21:16.719Z" },
 "panels": [
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (target) (sum_over_time({logtype=\"pgbouncer\"} |~ \"LOG stats\" | pattern \"<_> <_> stats: <xacts> xacts/s, <queries> queries/s, in <inbytesps> B/s, out <outbytesps> B/s, xact <xactus> us, query <queryus> us, wait <waitus> us\" | unwrap queries  [1m]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Wait Time (microseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (target) (sum_over_time({logtype=\"pgbouncer\"} |~ \"LOG stats\" | pattern \"<_> <_> stats: <xacts> xacts/s, <queries> queries/s, in <inbytesps> B/s, out <outbytesps> B/s, xact <xactus> us, query <queryus> us, wait <waitus> us\" | unwrap waitus  [1m]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Query Response Time (microseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 13 },
   "targets": [
    {
     "expr": "sum by (target) (sum_over_time({logtype=\"pgbouncer\"} |~ \"LOG stats\" | pattern \"<_> <_> stats: <xacts> xacts/s, <queries> queries/s, in <inbytesps> B/s, out <outbytesps> B/s, xact <xactus> us, query <queryus> us, wait <waitus> us\" | unwrap queryus  [1m]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Bytes IN per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (target) (sum_over_time({logtype=\"pgbouncer\"} |~ \"LOG stats\" | pattern \"<_> <_> stats: <xacts> xacts/s, <queries> queries/s, in <inbytesps> B/s, out <outbytesps> B/s, xact <xactus> us, query <queryus> us, wait <waitus> us\" | unwrap inbytesps [1m]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Bytes OUT per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "sum by (target) (sum_over_time({logtype=\"pgbouncer\"} |~ \"LOG stats\" | pattern \"<_> <_> stats: <xacts> xacts/s, <queries> queries/s, in <inbytesps> B/s, out <outbytesps> B/s, xact <xactus> us, query <queryus> us, wait <waitus> us\" | unwrap outbytesps [1m]))",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}